blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list),
    url(r'^post/(?P<id>[0-9]+)/$', views.post_detail, name='detail'),
    url(r'^post/new/$', views.post_new, name='new'),
    url(r'^post/(?P<id>[0-9]+)/edit/$', views.post_edit, name='edit'),
    url(r'^draft/$', views.post_draft_list, name='draft'),
    url(r'^post/(?P<id>[0-9]+)/publish/$', views.post_publish, name='publish'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm
from .models import Post


def post_list(request):
    posts = Post.objects.filter(published_date__isnull=False).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, id):
    post = get_object_or_404(Post, pk=id)
    return render(request, 'blog/post_detail.html', {'post': post})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:detail', id=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


def post_edit(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:detail', id=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('-created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})


def post_publish(request, id):
    post = get_object_or_404(Post, pk=id)
    post.publish()
    return redirect('blog:detail', id)

blog/templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的博客</title>
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
<div class="page-header">
      <a href="{% url 'blog:new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
    <a href="{% url 'blog:draft' %}" class="top-menu">
    <span class="glyphicon glyphicon-edit"></span></a>
    <h1><a href="/">My Study Blog</a></h1>

</div>
<div class="content">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>


</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="date">
        {% if post.published_date %}
            {{ post.published_date }}
        {% else %}
             <a class="btn btn-default" href="{% url 'blog:publish' post.pk %}">发布</a>
        {% endif %}
    <a class="btn btn-default" href="{% url 'blog:edit' post.pk %}">
    <span class="glyphicon glyphicon-pencil"></span></a>
    </div>
    <h1>{{ post.title }}</h1>
    <p>
        {{ post.text|linebreaks }}
    </p>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in posts %}
        <div class="post">
            <p>创建日期：{{ post.created_date|date:'Y-m-d' }}</p>
            <h1><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h1>
            <p>
                {{ post.text|truncatechars:200 }}
            </p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% block content %}
   <h1>添加/修改博客</h1>
    <form method="post" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
   <button type="submit" class="save btn btn-default">保存</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <h1><a href="/">My Study Blog</a></h1>
</div>
{% for post in posts %}
    <div>
        <p>发布日期：{{ post.published_date }}</p>
        <h1><a href="">{{ post.title }}</a></h1>
        <p>
            {{ post.text|linebreaks }}
        </p>
    </div>
{% endfor %}


</body>
</html>